 # config/packages/twig.yaml


twig:
    default_path: '%kernel.project_dir%/templates'
    cache:  false

    globals:
       mappath: '%env(MAPPATH)%'
       maproot: '%env(MAPROOT)%'
       #MapServer: "@MapServer"
