index:
  path: /
  controller: App\Controller\MainController::mainmenu

selectyear:
  path: /selectyear/{year}
  controller: App\Controller\MainController::selectyear

district_showone:
   path: /district/show/{dtid}
   controller: App\Controller\DistrictController::showone

district_edit:
   path: /district/edit/{dtid}
   controller: App\Controller\DistrictController::edit

district_heatmap:
   path: /district/heatmap/{dtid}
   controller: App\Controller\DistrictController::heatmap

pollingdistrict_showone:
   path: /pollingdistrict/show/{pdid}
   controller: App\Controller\PollingDistrictController::showone

pollingdistrict_edit:
   path: /pollingdistrict/edit/{pdid}
   controller: App\Controller\PollingDistrictController::edit

pollingdistrict_update:
    path:  /pollingdistrict/update/{pdid}
    controller: App\Controller\PollingDistrictController::update

pollingdistrict_showall:
   path: /pollingdistrict/showall
   controller: App\Controller\PollingDistrictController::showall

pollingdistrict_showstreets:
   path: /pollingdistrict/showstreets/{pdid}
   controller: App\Controller\PollingDistrictController::showstreets

pollingdistrict_newstreet:
   path: /pollingdistrict/newstreet/{dtid}/{pdid}
   controller: App\Controller\PollingDistrictController::newstreet

delivery_schedule:
   path: /delivery/scheduledelivery/{dvyid}
   controller: App\Controller\DeliveryController::scheduledelivery

delivery_schedulegroup:
   path: /delivery/schedulegroup/{dvyid}/{grpid}
   controller: App\Controller\DeliveryController::schedulegroup

delivery_schedulesubgroup:
   path: /delivery/schedulesubgroup/{dvyid}/{grpid}/{sgrpid}
   controller: App\Controller\DeliveryController::schedulesubgroup

delivery_schedulerounds:
   path: /delivery/schedulerounds/{dvyid}/{sgrpid}
   controller: App\Controller\DeliveryController::schedulerounds

delivery_scheduleround:
   path: /delivery/scheduleround/{dvyid}/{rndid}
   controller: App\Controller\DeliveryController::scheduleround


delivery_agents:
   path: /delivery/agents/{dvyid}
   controller: App\Controller\DeliveryController::showagents




delivery_update:
   path: /delivery/update/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::update
   defaults:
        rgsel: ALL

delivery_parseroadgroups:
   path: /delivery/parseroadgroups/{dvyid}
   controller: App\Controller\DeliveryController::parseroadgroups


delivery_delete:
   path: /delivery/delete/{dvyid}
   controller: App\Controller\DeliveryController::delete

delivery_edit:
   path: /delivery/edit/{dvyid}
   controller: App\Controller\DeliveryController::edit

delivery_new:
   path: /delivery/new/
   controller: App\Controller\DeliveryController::newdelivery

delivery_showcurrent:
   path: /delivery/showcurrent
   controller: App\Controller\DeliveryController::showcurrent



delivery_removeroadgroupfrommap:
   path: /delivery/removeroadgroup/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::removeroadgroup

delivery_addround:
   path: /delivery/addround/{dvyid}/
   controller: App\Controller\DeliveryController::addround
   requirements: { dvyid: \d+ }

delivery_makerounds:
   path: /delivery/makerounds/{dvyid}/
   controller: App\Controller\DeliveryController::makerounds


delivery_deleteround:
   path: /delivery/deleteround/{dvyid}/{rndid}
   controller: App\Controller\DeliveryController::deleteround



delivery_addroadgroup:
   path: /delivery/addroadgroup/{dvyid}/{rndid}/{rgid}
   controller: App\Controller\DeliveryController::addroadgroup

delivery_addallroadgroups:
   path: /delivery/addallroadgroups/{dvyid}/{rndid}/{rgsubgid}
   controller: App\Controller\DeliveryController::addallroadgroups


delivery_removeroadgroup:
   path: /delivery/removeroadgroup/{dvyid}/{rndid}/{rgid}
   controller: App\Controller\DeliveryController::removeroadgroup


delivery_addroadgroupstomap:
   path: /delivery/addround/{dvyid}/{rgid}
   controller: App\Controller\DeliveryController::addround

delivery_export:
   path: /delivery/export/{dvyid}
   controller: App\Controller\DeliveryController::exportxml

delivery_exportcsv:
    path: /delivery/exportcsv/{dvyid}
    controller: App\Controller\DeliveryController::exportcsv


delivery_manage:
   path: /delivery/manage/{dvyid}
   controller: App\Controller\DeliveryController::manage

delivery_updategroup:
   path: /delivery/updategroup/{dvyid}/{grpid}
   controller: App\Controller\DeliveryController::updategroup

round_manage_round:
   path: /round/managegroup/{dvyid}/{grpid}
   controller: App\Controller\RoundController::managegroup
   defaults:
        rgsel: ALL

round_manage_subgroup:
   path: /round/managesubgroup/{dvyid}/{grpid}/{sgrpid}
   controller: App\Controller\RoundController::managesubgroup

round_update:
   path: /round/updateround/{dvyid}/{grpid}/{sgrpid}
   controller: App\Controller\RoundController::updateround

round_update_subgroup:
   path: /round/updatesubgroup/{dvyid}/{grpid}/{sgrpid}
   controller: App\Controller\RoundController::updatesubgroup

round_update_group:
   path: /round/updategroup/{dvyid}/{grpid}
   controller: App\Controller\RoundController::updategroup

round_delete:
   path: /round/deleteround/{dvyid}/{rndid}
   controller: App\Controller\RoundController::deleteround

round_zero:
   path: /round/zeroround/{dvyid}/{rndid}
   controller: App\Controller\RoundController::zeroround

round_zerosubgroup:
   path: /round/zerosubgroup/{dvyid}/{grpid}/{sgrpid}
   controller: App\Controller\RoundController::zerosubgroup

round_updatestats:
   path: /round/update/{dvyid}/{rndid}
   controller: App\Controller\RoundController::updatefromroadgroups

seats_showone:
   path: /seat/show/{dtid}/{stid}
   controller: App\Controller\SeatController::showone

seats_showpds:
   path: /seat/showpds/{dtid}/{stid}
   controller: App\Controller\SeatController::showpds


seats_removepd:
   path: /seat/removepd/{dtid}/{stid}/{pdid}
   controller: App\Controller\SeatController::removepd

seats_showrgs:
   path: /seat/showrgs/{dtid}/{stid}
   controller: App\Controller\SeatController::showrgs

seats_edit:
   path: /seat/edit/{dtid}/{stid}
   controller: App\Controller\SeatController::edit

seats_newseat:
   path: /seat/new/{dtid}/{stid}
   controller: App\Controller\SeatController::edit
   defaults:
        stid: -1

seats_showall:
   path: /seat/showall/{dtid}
   controller: App\Controller\SeatController::showall

seats_addpd:
   path: /seat/addpollingdistrict/{dtid}/{stid}
   controller: App\Controller\SeatController::addpd



rggroups_all:
    path: /rggroup/showall
    controller: App\Controller\RggroupController::showall

rggroups_new:
    path: /rggroup/new
    controller: App\Controller\RggroupController::newrggroup

rggroups_show_one:
    path: /rggroup/show/{wdid}
    controller: App\Controller\RggroupController::showone

rggroups_edit:
    path: /rggroup/edit/{rgid}
    controller: App\Controller\RggroupController::edit

rggroups_heat:
    path: /rggroup/showheatmap/{rgid}
    controller: App\Controller\RggroupController::heatmap

rggroups_delete:
    path: /rggroup/delete/{rgid}
    controller: App\Controller\RggroupController::delete

rggroups_update:
    path: /rggroup/updategroup/{wdid}
    controller: App\Controller\RggroupController::updategroup

rggroups_export:
    path: /rggroup/export
    controller: App\Controller\DistrictController::export

rggroups_heatmap:
    path: /rggroup/heatmap
    controller: App\Controller\RggroupController::heatmap

rggroups_print:
    path: /rggroup/print
    controller: App\Controller\RggroupController::topdf

rgsubgroups_show_one:
    path: /rgsubgroup/show/{swdid}
    controller: App\Controller\RggroupController::showsubgroup

rgsubgroups_update:
    path: /rgsubgroup/update/{swdid}
    controller: App\Controller\RggroupController::updatesubgroup

rgsubgroups_new:
    path: /rgsubgroup/new/{wdid}
    controller: App\Controller\RggroupController::newsubgroup

rgsubgroups_add_roadgroup:
    path:  /rggroup/addroadgroup/{wdid}/{swdid}/{rgid}
    controller: App\Controller\RggroupController::addroadgroup


rgsubgroups_edit:
    path: /rgsubgroup/edit/{swdid}
    controller: App\Controller\RggroupController::editsubgroup

rgsubgroups_delete:
    path: /rgsubgroup/delete/{swdid}
    controller: App\Controller\RggroupController::deletesubgroup

roadgroups_show_all:
    path: /roadgroup/showall
    controller: App\Controller\RoadgroupController::showall

roadgroups_show_one:
    path: /roadgroup/show/{stid}/{rgid}
    controller: App\Controller\RoadgroupController::showone

roadgroups_show_oneb:
    path: /roadgroup/showone/{rgid}
    controller: App\Controller\RoadgroupController::showone

roadgroups_new:
    path: /roadgroup/new/{wdid}/{swdid}
    controller: App\Controller\RoadgroupController::newRG

roadgroups_edit:
    path: /roadgroup/edit/{rgid}
    controller: App\Controller\RoadgroupController::edit

roadgroups_removefromsubgroup:
    path: /roadgroup/removefromsubgroup/{rgid}
    controller: App\Controller\RoadgroupController::removefromsubgroup

roadgroups_delete:
    path: /roadgroup/delete/{rgid}
    controller: App\Controller\RoadgroupController::delete

roadgroups_newstreet:
    path: /roadgroup/newstreet/{rgid}
    controller: App\Controller\RoadgroupController::newstreet

roadgroups_upload:
    path: /roadgroup/upload
    controller: App\Controller\RoadgroupController::upload

roadgroups_update:
    path: /roadgroup/update/{rgid}
    controller: App\Controller\RoadgroupController::updateroadgroup

roadgroups_pdsd:
    path: /roadgroup/showpds
    controller: App\Controller\RoadgroupController::showpds

streets_all:
    path: /street/showall
    controller: App\Controller\StreetController::showall

streets_filters:
    path: /street/filters
    controller: App\Controller\StreetController::filters

streets_search:
    path: /street/search
    controller: App\Controller\StreetController::search

streets_problems:
    path: /street/problems
    controller: App\Controller\StreetController::showproblems

streets_problem:
    path: /street/problem/{problemtype}
    controller: App\Controller\StreetController::showproblems

street_edit:
    path: /street/edit/{rdseq}
    controller: App\Controller\StreetController::streetedit
    defaults:
        rdpart: /

street_editbyseq:
    path: /street/editbyseq/{rdseq}
    controller: App\Controller\StreetController::streetedit


street_editgroup:
    path: /street/editgroup/{rdseq}
    controller: App\Controller\StreetController::streetviewgroupbyseq


street_viewgroup:
    path: /street/viewgroup/{rdname}
    controller: App\Controller\StreetController::streetviewgroupbyname

street_viewgroupbyseq:
    path: /street/viewgroupbyseq/{rdseq}
    controller: App\Controller\StreetController::streetviewgroupbyseq


street_remove:
     path: /street/remove/{rgid}/{rdseq}
     controller: App\Controller\StreetController::streetremove


street_add:
     path: /street/add/{rgid}
     controller: App\Controller\StreetController::streetadd

street_import:
     path: /street/streetimport
     controller: App\Controller\StreetController::streetimport


street_delete:
    path: /street/delete/{stseq}
    controller: App\Controller\StreetController::streetdelete
    defaults:
        stpart: null

street_replicate:
    path: /street/replicate/{stseq}
    controller: App\Controller\StreetController::streetreplicate


street_merge:
    path: /street/groupops
    controller: App\Controller\StreetController::streetgroupops

