index:
  path: /
  controller: App\Controller\MainController::mainmenu

selectyear:
  path: /selectyear/{year}
  controller: App\Controller\MainController::selectyear

district_showone:
   path: /district/show/{drid}
   controller: App\Controller\DistrictController::showone

district_exportxml:
    path: /district/exportxml/{drid}
    controller: App\Controller\DistrictController::exportxml

district_exportcsv:
    path: /district/exportcsv/{drid}
    controller: App\Controller\DistrictController::exportcsv

pollingdistrict_showone:
   path: /pollingdistrict/show/{pdid}
   controller: App\Controller\PollingDistrictController::showone

delivery_showone:
   path: /delivery/schedule/{dvyid}
   controller: App\Controller\DeliveryController::schedule


delivery_mapone:
   path: /delivery/mapschedule/{dvyid}
   controller: App\Controller\DeliveryController::mapschedule

delivery_viewdetail:
   path: /delivery/viewdetail/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::viewdetail

delivery_manage:
   path: /delivery/manage/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::manage
   defaults:
        rgsel: ALL

delivery_update:
   path: /delivery/update/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::update
   defaults:
        rgsel: ALL

delivery_parseroadgroups:
   path: /delivery/parseroadgroups/{dvyid}
   controller: App\Controller\DeliveryController::parseroadgroups


delivery_delete:
   path: /delivery/delete/{dvyid}
   controller: App\Controller\DeliveryController::delete

delivery_edit:
   path: /delivery/edit/{dvyid}
   controller: App\Controller\DeliveryController::edit

delivery_new:
   path: /delivery/new/
   controller: App\Controller\DeliveryController::newdelivery

delivery_showcurrent:
   path: /delivery/showcurrent
   controller: App\Controller\DeliveryController::showcurrent

delivery_removeroadgroup:
   path: /delivery/removeround/{dvyid}/{rgid}
   controller: App\Controller\DeliveryController::removeround

delivery_removeroadgroupfrommap:
   path: /delivery/removeroadgroup/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::removeroadgroup

delivery_addroadgroups:
   path: /delivery/addroadgroup/{dvyid}/{rgsel}
   controller: App\Controller\DeliveryController::addroadgroup

delivery_addroadgroupstomap:
   path: /delivery/addround/{dvyid}/{rgid}
   controller: App\Controller\DeliveryController::addround

delivery_export:
   path: /delivery/export/{dvyid}
   controller: App\Controller\DeliveryController::exportxml

delivery_exportcsv:
    path: /delivery/exportcsv/{dvyid}
    controller: App\Controller\DeliveryController::exportcsv


seats_showone:
   path: /seat/show/{dtid}/{stid}
   controller: App\Controller\SeatController::showone

seats_showpds:
   path: /seat/showpds/{dtid}/{stid}
   controller: App\Controller\SeatController::showpds


seats_removepd:
   path: /seat/removepd/{dtid}/{stid}/{pdid}
   controller: App\Controller\SeatController::removepd

seats_showrgs:
   path: /seat/showrgs/{dtid}/{stid}
   controller: App\Controller\SeatController::showrgs

seats_edit:
   path: /seat/edit/{dtid}/{stid}
   controller: App\Controller\SeatController::edit

seats_newseat:
   path: /seat/new/{dtid}/{stid}
   controller: App\Controller\SeatController::edit
   defaults:
        stid: -1

seats_showall:
   path: /seat/showall/{dtid}
   controller: App\Controller\SeatController::showall

seats_addpd:
   path: /seat/addpollingdistrict/{dtid}/{stid}
   controller: App\Controller\SeatController::addpd

pd_showall:
   path: /pollingdistrict/showall
   controller: App\Controller\PollingDistrictController::showall

rggroups_all:
    path: /rggroup/showall
    controller: App\Controller\RggroupController::showall

rggroups_new:
    path: /rggroup/new
    controller: App\Controller\RggroupController::newrggroup

rggroups_show_one:
    path: /rggroup/show/{wdid}
    controller: App\Controller\RggroupController::showone

rggroups_edit:
    path: /rggroup/edit/{rgid}
    controller: App\Controller\RggroupController::edit

rggroups_delete:
    path: /rggroup/delete/{rgid}
    controller: App\Controller\RggroupController::delete

rggroups_export:
    path: /rggroup/export
    controller: App\Controller\DistrictController::export

rggroups_heatmap:
    path: /rggroup/heatmap
    controller: App\Controller\RggroupController::heatmap

rggroups_print:
    path: /rggroup/print
    controller: App\Controller\RggroupController::topdf

rgsubgroups_show_one:
    path: /rgsubgroup/show/{swdid}
    controller: App\Controller\RggroupController::showsubgroup

rgsubgroups_new:
    path: /rgsubgroup/new/{wdid}
    controller: App\Controller\RggroupController::newsubgroup

rgsubgroups_edit:
    path: /rgsubgroup/edit/{swdid}
    controller: App\Controller\RggroupController::editsubgroup

rgsubgroups_delete:
    path: /rgsubgroup/delete/{swdid}
    controller: App\Controller\RggroupController::deletesubgroup

roadgroups_show_all:
    path: /roadgroup/showall
    controller: App\Controller\RoadgroupController::showall

roadgroups_show_one:
    path: /roadgroup/show/{stid}/{rgid}
    controller: App\Controller\RoadgroupController::showone

roadgroups_show_oneb:
    path: /roadgroup/showone/{rgid}
    controller: App\Controller\RoadgroupController::showone

roadgroups_new:
    path: /roadgroup/new/{wdid}/{swdid}
    controller: App\Controller\RoadgroupController::newRG

roadgroups_edit:
    path: /roadgroup/edit/{rgid}
    controller: App\Controller\RoadgroupController::edit

roadgroups_delete:
    path: /roadgroup/delete/{rgid}
    controller: App\Controller\RoadgroupController::delete

roadgroups_newstreet:
    path: /roadgroup/newstreet/{rgid}
    controller: App\Controller\RoadgroupController::newstreet

roadgroups_upload:
    path: /roadgroup/upload
    controller: App\Controller\RoadgroupController::upload

roadgroups_newkml:
    path: /roadgroup/newkml/{rgid}
    controller: App\Controller\RoadgroupController::exportkml

roadgroups_pdsd:
    path: /roadgroup/showpds
    controller: App\Controller\RoadgroupController::showpds

streets_all:
    path: /street/showall
    controller: App\Controller\StreetController::showall

streets_filters:
    path: /street/filters
    controller: App\Controller\StreetController::filters

streets_search:
    path: /street/search
    controller: App\Controller\StreetController::search

streets_problems:
    path: /street/problems
    controller: App\Controller\StreetController::showproblems

streets_problem:
    path: /street/problem/{problemtype}
    controller: App\Controller\StreetController::showproblems

street_edit:
    path: /street/edit/{rdname}/{rdpart}
    controller: App\Controller\StreetController::streetedit
    defaults:
        rdpart: /

street_editgroup:
    path: /street/editgroup/{name}
    controller: App\Controller\StreetController::streetviewgroup


street_viewgroup:
    path: /street/viewgroup/{name}
    controller: App\Controller\StreetController::streetviewgroup

street_remove:
     path: /street/remove/{rgid}/{stname}/{stpart}
     controller: App\Controller\StreetController::streetremove
     defaults:
        stpart: null

street_add:
     path: /street/add/{rgid}
     controller: App\Controller\StreetController::streetadd



street_delete:
    path: /street/delete/{stname}/{stpart}
    controller: App\Controller\StreetController::streetdelete
    defaults:
        stpart: null

street_replicate:
    path: /street/replicate/{stname}/{stpart}
    controller: App\Controller\StreetController::streetreplicate
    defaults:
        stpart: null

street_merge:
    path: /street/groupops
    controller: App\Controller\StreetController::streetgroupops

